import { NextResponse } from 'next/server';
import { getProject, getScans, getFindings } from '@/lib/storage';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

function cleanFilePath(p: string | null): string {
  return p?.replace(/\/tmp\/vlayer-scan-[^/]+\/[^/]+\//, '') ?? '';
}

function severityOrder(s: string): number {
  const map: Record<string, number> = { critical: 0, high: 1, medium: 2, low: 3, info: 4 };
  return map[s] ?? 5;
}

function addHeader(doc: jsPDF, projectName: string, reportType: string) {
  const pageWidth = doc.internal.pageSize.getWidth();
  // Dark green header bar
  doc.setFillColor(6, 95, 70); // #065F46
  doc.rect(0, 0, pageWidth, 28, 'F');
  // Logo text
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(255, 255, 255);
  doc.text('VLayer', 14, 12);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text('HIPAA Compliance Scanner', 14, 19);
  // Right side
  doc.setFontSize(9);
  doc.text(projectName, pageWidth - 14, 12, { align: 'right' });
  doc.text(reportType, pageWidth - 14, 19, { align: 'right' });
}

function addFooter(doc: jsPDF, pageNum: number, totalPages: number) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(7);
  doc.setTextColor(150, 150, 150);
  doc.text(`Generated by VLayer - HIPAA Compliance Scanner | ${new Date().toISOString()}`, 14, pageHeight - 8);
  doc.text(`Page ${pageNum} of ${totalPages}`, pageWidth - 14, pageHeight - 8, { align: 'right' });
}

const REPORT_TYPE_LABELS: Record<string, string> = {
  full_compliance: 'Full Compliance Report',
  executive_summary: 'Executive Summary',
  technical_findings: 'Technical Findings',
  remediation_plan: 'Remediation Plan',
};

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { project_id, report_type = 'full_compliance', sections = [] } = body;

    if (!project_id) {
      return NextResponse.json({ error: 'project_id is required' }, { status: 400 });
    }

    const project = await getProject(project_id);
    if (!project) {
      return NextResponse.json({ error: 'Project not found' }, { status: 404 });
    }

    const scans = await getScans(project_id);
    const latestScan = scans[0] ?? null;
    const findings = latestScan ? await getFindings(project_id, latestScan.id) : [];

    // Sort findings by severity
    const sortedFindings = [...findings].sort((a, b) => severityOrder(a.severity) - severityOrder(b.severity));

    const reportLabel = REPORT_TYPE_LABELS[report_type] || 'Compliance Report';
    const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
    const pageWidth = doc.internal.pageSize.getWidth();
    let y = 0;

    // ========================
    // PAGE 1: Title + Executive Summary
    // ========================
    addHeader(doc, project.name, reportLabel);
    y = 38;

    // Title
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(22);
    doc.setTextColor(30, 30, 30);
    doc.text(reportLabel, 14, y);
    y += 10;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);
    doc.setTextColor(100, 100, 100);
    doc.text(`Project: ${project.name}`, 14, y);
    y += 6;
    doc.text(`Generated: ${new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}`, 14, y);
    y += 6;
    if (project.repoUrl) {
      doc.text(`Repository: ${project.repoUrl}`, 14, y);
      y += 6;
    }
    y += 4;

    // Divider
    doc.setDrawColor(200, 200, 200);
    doc.line(14, y, pageWidth - 14, y);
    y += 10;

    // Executive Summary section
    if (report_type !== 'remediation_plan') {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(16);
      doc.setTextColor(30, 30, 30);
      doc.text('Executive Summary', 14, y);
      y += 10;

      // Score box
      const boxWidth = (pageWidth - 42) / 3;
      const boxes = [
        { label: 'Compliance Score', value: `${project.complianceScore}/100`, sub: `Grade ${project.grade}` },
        { label: 'Status', value: project.status.replace('_', ' ').toUpperCase(), sub: '' },
        { label: 'Total Findings', value: `${latestScan?.totalFindings ?? 0}`, sub: `${latestScan?.filesScanned ?? 0} files scanned` },
      ];

      boxes.forEach((box, i) => {
        const bx = 14 + i * (boxWidth + 7);
        // Box background
        doc.setFillColor(245, 247, 250);
        doc.roundedRect(bx, y, boxWidth, 30, 3, 3, 'F');
        // Label
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8);
        doc.setTextColor(120, 120, 120);
        doc.text(box.label, bx + 5, y + 8);
        // Value
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(16);
        doc.setTextColor(30, 30, 30);
        doc.text(box.value, bx + 5, y + 20);
        // Sub
        if (box.sub) {
          doc.setFont('helvetica', 'normal');
          doc.setFontSize(7);
          doc.setTextColor(150, 150, 150);
          doc.text(box.sub, bx + 5, y + 26);
        }
      });
      y += 40;

      // Findings by severity
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(12);
      doc.setTextColor(30, 30, 30);
      doc.text('Findings by Severity', 14, y);
      y += 8;

      const summary = project.findingsSummary;
      const severities = [
        { label: 'Critical', count: summary.critical ?? 0, color: [220, 38, 38] as [number, number, number] },
        { label: 'High', count: summary.high ?? 0, color: [249, 115, 22] as [number, number, number] },
        { label: 'Medium', count: summary.medium ?? 0, color: [245, 158, 11] as [number, number, number] },
        { label: 'Low', count: summary.low ?? 0, color: [34, 197, 94] as [number, number, number] },
        { label: 'Info', count: summary.info ?? 0, color: [100, 116, 139] as [number, number, number] },
      ];

      const barMaxWidth = pageWidth - 80;
      const maxCount = Math.max(...severities.map(s => s.count), 1);

      severities.forEach((sev) => {
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(9);
        doc.setTextColor(80, 80, 80);
        doc.text(`${sev.label}`, 14, y + 3);
        doc.text(`${sev.count}`, pageWidth - 14, y + 3, { align: 'right' });

        // Bar background
        doc.setFillColor(235, 235, 235);
        doc.roundedRect(50, y - 1, barMaxWidth, 5, 2, 2, 'F');
        // Bar fill
        if (sev.count > 0) {
          const barWidth = Math.max((sev.count / maxCount) * barMaxWidth, 3);
          doc.setFillColor(...sev.color);
          doc.roundedRect(50, y - 1, barWidth, 5, 2, 2, 'F');
        }
        y += 10;
      });
      y += 5;
    }

    // ========================
    // FINDINGS TABLE
    // ========================
    if (report_type !== 'executive_summary' && sortedFindings.length > 0) {
      // Check if we need a new page
      if (y > 200) {
        doc.addPage();
        addHeader(doc, project.name, reportLabel);
        y = 38;
      }

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(16);
      doc.setTextColor(30, 30, 30);
      doc.text(report_type === 'remediation_plan' ? 'Remediation Plan' : 'Detailed Findings', 14, y);
      y += 10;

      const tableData = sortedFindings.map((f) => [
        f.severity.toUpperCase(),
        f.title,
        cleanFilePath(f.filePath) || '-',
        f.lineNumber ? String(f.lineNumber) : '-',
        f.hipaaReference || '-',
      ]);

      autoTable(doc, {
        startY: y,
        head: [['Severity', 'Title', 'File', 'Line', 'HIPAA Ref']],
        body: tableData,
        margin: { left: 14, right: 14 },
        styles: {
          fontSize: 7,
          cellPadding: 3,
          textColor: [50, 50, 50],
          lineColor: [220, 220, 220],
          lineWidth: 0.2,
        },
        headStyles: {
          fillColor: [6, 95, 70],
          textColor: [255, 255, 255],
          fontSize: 8,
          fontStyle: 'bold',
        },
        columnStyles: {
          0: { cellWidth: 18, fontStyle: 'bold' },
          1: { cellWidth: 60 },
          2: { cellWidth: 55, fontSize: 6 },
          3: { cellWidth: 12, halign: 'center' },
          4: { cellWidth: 30, fontSize: 6 },
        },
        didParseCell: (data) => {
          if (data.section === 'body' && data.column.index === 0) {
            const val = String(data.cell.raw).toLowerCase();
            if (val === 'critical') data.cell.styles.textColor = [220, 38, 38];
            else if (val === 'high') data.cell.styles.textColor = [249, 115, 22];
            else if (val === 'medium') data.cell.styles.textColor = [245, 158, 11];
            else if (val === 'low') data.cell.styles.textColor = [34, 197, 94];
          }
        },
        didDrawPage: () => {
          addHeader(doc, project.name, reportLabel);
        },
      });

      y = (doc as any).lastAutoTable?.finalY ?? y + 20;
    }

    // ========================
    // REMEDIATION RECOMMENDATIONS
    // ========================
    if (report_type === 'full_compliance' || report_type === 'remediation_plan') {
      const criticalFindings = sortedFindings.filter(f => f.severity === 'critical' || f.severity === 'high');

      if (criticalFindings.length > 0) {
        if (y > 220) {
          doc.addPage();
          addHeader(doc, project.name, reportLabel);
          y = 38;
        }

        doc.setFont('helvetica', 'bold');
        doc.setFontSize(16);
        doc.setTextColor(30, 30, 30);
        doc.text('Remediation Recommendations', 14, y);
        y += 10;

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8);
        doc.setTextColor(100, 100, 100);
        doc.text('Prioritized by severity. Address critical issues first.', 14, y);
        y += 8;

        criticalFindings.slice(0, 20).forEach((f, i) => {
          if (y > 265) {
            doc.addPage();
            addHeader(doc, project.name, reportLabel);
            y = 38;
          }

          const sevColor: [number, number, number] = f.severity === 'critical' ? [220, 38, 38] : [249, 115, 22];
          doc.setFont('helvetica', 'bold');
          doc.setFontSize(8);
          doc.setTextColor(...sevColor);
          doc.text(`${i + 1}. [${f.severity.toUpperCase()}]`, 14, y);

          doc.setTextColor(30, 30, 30);
          doc.setFontSize(9);
          const titleLines = doc.splitTextToSize(f.title, pageWidth - 60);
          doc.text(titleLines, 40, y);
          y += titleLines.length * 4 + 2;

          if (f.recommendation) {
            doc.setFont('helvetica', 'normal');
            doc.setFontSize(8);
            doc.setTextColor(80, 80, 80);
            const recLines = doc.splitTextToSize(`Recommendation: ${f.recommendation}`, pageWidth - 44);
            doc.text(recLines, 18, y);
            y += recLines.length * 3.5 + 2;
          }

          if (f.filePath) {
            doc.setFont('helvetica', 'normal');
            doc.setFontSize(7);
            doc.setTextColor(120, 120, 120);
            doc.text(`File: ${cleanFilePath(f.filePath)}${f.lineNumber ? `:${f.lineNumber}` : ''}`, 18, y);
            y += 4;
          }

          y += 3;
        });
      }
    }

    // Add page numbers
    const totalPages = doc.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      addFooter(doc, i, totalPages);
    }

    // Output buffer
    const pdfBuffer = Buffer.from(doc.output('arraybuffer'));

    return new Response(pdfBuffer, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="vlayer-${project.name.toLowerCase().replace(/\s+/g, '-')}-${report_type}-${new Date().toISOString().slice(0, 10)}.pdf"`,
      },
    });
  } catch (error: any) {
    console.error('[reports/generate] Error:', error);
    return NextResponse.json({ error: error.message || 'Failed to generate report' }, { status: 500 });
  }
}
